Script = <Newline>* Scene (<Newline>+ Scene)* <Newline>*
Scene = Heading <Newline>+ Part (<Newline>+ Part)*
Heading = ('INT.' | 'EXT.' | <'.'>) #'[A-Z\- ]+'
<Part> = Dialogue
Newline = '\n'
Dialogue = Character <Newline> (Parenthetical <Newline>)? Talk (<Newline> Parenthetical <Newline> Talk)*
Character = #'[A-Z\- ]+'
Talk = !'(' Line (<Newline> Line)*
Parenthetical = <'('> Line (<Newline> Line)* <')'>
Line = #'.'+

